server:
  port: 8080

spring:
  # datasource
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myserver:8505/activities?useUnicode=true&characterEncoding=utf-8&useSSL=false
  # activity
  activiti:
    database-schema: activities
    database-schema-update: true  # strategy for database
    db-history-used: true
    check-process-definitions: false # auto deployed

# log
logging:
  level:
    com.jiang.workflow: DEBUG

# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
  global-config:
    banner: false # 是否控制台 print mybatis-plus 的 LOGO

