server:
  port: 8080

spring:
  # datasource
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://myserver:8505/activities?useUnicode=true&characterEncoding=utf-8&useSSL=false
  # activity
  activiti:
    database-schema: activities
    database-schema-update: true
    history-level: full
    db-history-used: true


# log
logging:
  level:
    com.jiang: INFO

# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 是否开启自动驼峰命名规则
  global-config:
    banner: false # 是否控制台 print mybatis-plus 的 LOGO

